### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by s101d1** [saman2007/async-connect-flash#1]
I have some suggestions:

1. There should be a way to retrieve the whole `flash` object like in `connect-flash` package with the `req.flash()` function (if no key argument provided, it should return the whole session's flash object).

2. I found out the `req.setFlash` function inserts a single string value instead of array of string values like in `connect-flash`. So `await req.setFlash("error", "There is an error.")` would result into:

```
"flash": {
    "error": "There is an error."
}
```

In `connect-flash` with `req.flash("error", "There is an error.")` function, it would result into:

```
"flash": {
    "error": [
        "There is an error."
    ]
}
```

I suggest to make the `async-connect-flash` having same behavior as `connect-flash` in this regard.

And perhaps make the `req.getFlash()` and `req.setFlash()` function names same as functions in the `connect-flash` as well (so they become `req.flash(key)` and `req.flash(key, value)` respectively).

**Comment by saman2007** [comment]
Hello.
Thanks for your suggestions, i will add some of them as sson as possible.
